### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ceccode** [start-react/native-starter-kit#1]
Hi, 
I have this error during `npm install`

```
npm WARN EPEERINVALID react-native-navbar@1.1.2 requires a peer of react-native@^0.16 but none was installed.
```

My ENV:
- node 5.1.0
- npm 3.3.12
- react-native-cli: 0.1.7

Thanks for help

**Comment by sankhadeeproy007** [comment]
Try installing an older version of `react-native-navbar` from here https://github.com/react-native-fellowship/react-native-navbar

**Comment by ceccode** [comment]
It works with  react-native-navbar 1.0.0.
