### ISSUE TITLE
Warning: Failed propType: Invalid props.style key 'color' supplied to [ 'View' | 'RCTView' ]

### ISSUE THREAD

**Issue by geirman** [start-react/native-starter-kit#10]
in both iOS and Android simulators, I'm receiving these warnings after clicking "Login"
<img width="1183" alt="2016-06-21_1745" src="https://cloud.githubusercontent.com/assets/1640318/16251105/2927301e-37d8-11e6-9b5e-7918aa1fb371.png">

**Comment by geirman** [comment]
<img width="413" alt="2016-06-21_1747" src="https://cloud.githubusercontent.com/assets/1640318/16251117/440d4c56-37d8-11e6-9ae2-74ff2d43a02b.png">

**Comment by geirman** [comment]
I believe the error is occurring in /native-base/Components/Widgets/Button.js, but I haven't been able to locate it yet.

**Comment by sankhadeeproy007** [comment]
Thanks for pointing it out. It's in line 146. Just replace with
`return React.cloneElement(this.props.children)`

**Comment by sankhadeeproy007** [comment]
Will fix with next update.

**Comment by geirman** [comment]
Are you talking about this [`L146`](https://github.com/GeekyAnts/NativeBase/blob/master/Components/Widgets/Button.js#L146)?

If so, I made the change then rebuilt the project `react-native run-ios`, but it didn't solve the issue. Am I doing something wrong?

**Comment by sankhadeeproy007** [comment]
[Button.js.zip](https://github.com/start-react/native-starter-kit/files/328402/Button.js.zip)
Extract and try this one maybe.

**Comment by geirman** [comment]
Unfortunately not. 

I copied the new file into `/node_modules/native-base/Components/Widgets/`... and replaced Button.js, I stopped the package server, ran `react-native run-ios` and the problem persists

**Comment by geirman** [comment]
You should reopen this until it's actually fixed

**Comment by sankhadeeproy007** [comment]
It's more of a native-base issue. Please raise a issue in that repo.

**Comment by geirman** [comment]
Good point
