### ISSUE TITLE
Getting _reactNativeRouterFlex error on clicking login button

### ISSUE THREAD

**Issue by abhilashdonepudi** [start-react/native-starter-kit#105]
_reactNativeRouterFlex.Actions.Home is not a function. Any way to resolve this issue?

**Comment by Jasbir23** [comment]
@abhilashdonepudi did u use the latest version of master for this? Also, please attach some more information with this. Unable to replicate.

**Comment by abhilashdonepudi** [comment]
Yes. Downloaded Master. I was able to integrate react-navigation and fix the navigation for now.

![screen shot 2017-06-13 at 3 27 21 pm](https://user-images.githubusercontent.com/881822/27229298-b4245dd2-5270-11e7-8816-af23edc57bf9.png)

**Comment by Jasbir23** [comment]
@abhilashdonepudi React-navigation is already merged to the master.
 I am unable to replicate any such error in the app. Please get back on this with some more information.

**Comment by SupriyaKalghatgi** [comment]
@abhilashdonepudi Any updates?

**Comment by abhilashdonepudi** [comment]
Thanks for getting back to me. You can close this issue.
