### ISSUE TITLE
Why React Native Router Flux removed base code??

### ISSUE THREAD

**Issue by iiitmahesh** [start-react/native-starter-kit#108]
Why React Native Router Flux removed base code??

Is there any specific reason for that? 

(Please update readme)

**Comment by Jasbir23** [comment]
@iiitmahesh yes we had a couple of reasons, will include it in the README.

**Comment by Jasbir23** [comment]
https://github.com/start-react/native-starter-kit/blob/master/README.md
@iiitmahesh
