### ISSUE TITLE
Disable drawer gesture for Drawer

### ISSUE THREAD

**Issue by gouravsood** [start-react/native-starter-kit#116]
I have used this amazing starter kit to spin up for a small personal project. 

I am facing issue with Drawer gesture effect. 

After logging in, if I swipe from left to right, then app log me out and then I have login again. Can anyone please suggest how I can either stop the gesture effect from drawer or even if user swipe, then control the logout to happen?

**Comment by SupriyaKalghatgi** [comment]
@gouravsood which branch?

**Comment by gouravsood** [comment]
@SupriyaKalghatgi just pulled the latest code and using master branch code as base of my app.

**Comment by cwagner22** [comment]
Maybe `this.props.navigation.reset` should be used instead of `this.props.navigation.navigate` in `login/index.js` so the user can't go back to the login page.

**Comment by gouravsood** [comment]
Thanks @cwagner22. I have used reset navigation after login in my forked app and its working now. Reference code below:

https://github.com/gouravsood/native-starter-kit

@SupriyaKalghatgi  you can also plan to fix it in base app.

**Comment by SupriyaKalghatgi** [comment]
This repo is deprecated
Please check [ReactNativeSeed.com](https://reactnativeseed.com/)
