### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by hsvlz** [start-react/native-starter-kit#12]
Hi, very good job with this project!

Can I perhaps make a few suggestions regarding your code?
- you have a few unused definitions & code in multiple files - are you planning to use it?
- you are using a subscribe on the store in AppNavigator.js (this.props.store.getState().drawer.drawerState == 'opened') but as you are using redux, you surely could replace that with a reducer & mapStateToProps.
- could you perhaps consider using redux-act to reduce a lot the boilerplate definition of actions & reducers? (this would allow you to delete about 40-50 lines...)

Otherwise, excellent job! If you continue in that direction, I will definitely buy one of your premium packs!

Hsvlz.

**Comment by SupriyaKalghatgi** [comment]
@hsvlz Thank you for your suggestions.
Optimising our code is on our priority list. The upcoming version of Native Starter Kit would have these and also updated versions of [React Native](https://github.com/facebook/react-native) and [NativeBase](http://nativebase.io/documentation)

**Comment by hsvlz** [comment]
@SupriyaKalghatgi , do you plan to add unit tests too? Is there proper unittesting in the premium version?

**Comment by alfondotnet** [comment]
Also, isn't it a concern for you guys having side effects in the `route` reducer?, shouldn't these go in thunks for example?
