### ISSUE TITLE
react version problem 

### ISSUE THREAD

**Issue by ydwlaa** [start-react/native-starter-kit#120]
Hi there, 

I was trying to npm install, but got five warnings. 

npm WARN redux-form@6.8.0 requires a peer of react@^15.0.0 but none was installed.
npm WARN @shoutem/animation@0.8.10 requires a peer of react@^15.0.0 but none was installed.
npm WARN native-base-shoutem-theme@0.1.4 requires a peer of react@>=15.1.0 but none was installed.
npm WARN jest-react-native@17.0.0 requires a peer of whatwg-fetch@^1.0.0 but none was installed.
npm WARN react-test-renderer@15.3.2 requires a peer of react@^15.3.2 but none was installed.

My package.json is: 

"dependencies": {
    "color": "^0.11.3",
    "lodash": "^4.13.1",
    "moment": "^2.13.0",
    "native-base": "2.1.4",
    "react": "16.0.0-alpha.12",
    "react-native": "0.45.1",
    "react-native-code-push": "2.0.1-beta",
    "react-native-easy-grid": "0.1.8",
    "react-native-modalbox": "^1.3.4",
    "react-navigation": "1.0.0-beta.11",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-form": "^6.7.0",
    "redux-persist": "^4.0.0",
    "redux-thunk": "^2.2.0",
    "remote-redux-devtools": "^0.5.0"
  },

the version of react is latest, why still need old one ?

**Comment by SupriyaKalghatgi** [comment]
@ydwlaa Apart from warnings, could you build the app successfully?

**Comment by ydwlaa** [comment]
Yes, I think it builds successfully, but cannot run.

**Comment by SupriyaKalghatgi** [comment]
@ydwlaa 
> cannot run

Is it on iOS?
If yes try to `Run`(Cmd + R) after `Build`(Cmd + B)

**Comment by ydwlaa** [comment]
No, it is android emulator on windows. when I run it, the red screen comes up in the emulator

**Comment by SupriyaKalghatgi** [comment]
@ydwlaa Found it working?
