### ISSUE TITLE
What does the @ symbol do in javascript imports?

### ISSUE THREAD

**Issue by redochka** [start-react/native-starter-kit#129]
in src/index.js i see imports like this:

<pre>

// Consts and Libs
import { AppStyles } from '@theme/';
import AppRoutes from '@navigation/';
import Analytics from '@lib/analytics';
</pre>

What does the @ symbol do in javascript imports?

**Comment by sanketsahu** [comment]
https://stackoverflow.com/questions/42711175/what-does-the-symbol-do-in-javascript-imports

**Comment by redochka** [comment]
i have found this stackoverflow before, but the accepted response refers to `babel-plugin-root-import` however there is no trace of `babel-plugin-root-import` in the `native-starter-kit` repo. Can you confirm if `babel-plugin-root-import` is being used here?
