### ISSUE TITLE
Drawer Navigating Animation

### ISSUE THREAD

**Issue by WebTalentTop** [start-react/native-starter-kit#130]
When I navigate to other screens, the hidden drawer flickers between them.
I think this is not a right way to show it when navigating.
Is there anyone to help me to resolve this issue?
Thanks

**Comment by SupriyaKalghatgi** [comment]
Please check the ReadMe
This repo is deprecated
Refer [ReactNativeSeed.com](https://reactnativeseed.com/)

**Comment by WebTalentTop** [comment]
Hello, Supriya....Thanks for your info.
Can you please confirm this is right repo?
https://github.com/GeekyAnts/react-native-native-base-seed
But the seed project has no samples how to use navigation

**Comment by SupriyaKalghatgi** [comment]
@WebTalentTop No thats not the right one
If you check ReadMe of https://github.com/GeekyAnts/react-native-native-base-seed, it says `No Longer Maintained`

**Comment by WebTalentTop** [comment]
Help me. which is one similar as this native-starter kit?
I just have problems with Navigator and I want to replace it as CardStack Navigator.
The one I found has a structure for navigation but no sample screen is involved.

**Comment by SupriyaKalghatgi** [comment]
@WebTalentTop Refer the link [ReactNativeSeed.com](https://reactnativeseed.com/) and go through the possible options of your desire to get ready to run starter kit

**Comment by WebTalentTop** [comment]
OKay...let me check out the newly downloaded source

**Comment by gianpaj** [comment]
🙃 https://help.github.com/articles/archiving-repositories/

**Comment by SupriyaKalghatgi** [comment]
@gianpaj Yes we know that!
But we dont want to archive this repository at this moment
