### ISSUE TITLE
Picker itemTextStyle,itemTextStyle,textStyle not working

### ISSUE THREAD

**Issue by YogarajRamesh** [start-react/native-starter-kit#131]
<Picker
                                    iosHeader="Sub-Category"
                                    placeholder="Select your SIM"
                                    placeholderStyle={{ color: "#bfc6ea" }} 
                                    selectedValue={this.state.selected1}
                                    onValueChange={this.onValueChange.bind(this)}
                                    itemStyle={{ fontSize:18, color: '#d00'}
                                    itemTextStyle={{ fontSize:18, color: '#d00',fontFamily:"Montserrat-Regular" }}
                                    textStyle={{ fontSize:16, color: '#d00',fontFamily:"Montserrat-Regular" }}
                                    >

**Comment by SupriyaKalghatgi** [comment]
Please check ReadMe

![image](https://user-images.githubusercontent.com/13464885/38989639-28d61596-43f5-11e8-9176-25fbce06409e.png)
