### ISSUE TITLE
BackAndroid issue

### ISSUE THREAD

**Issue by aliajoudanian** [start-react/native-starter-kit#14]
Hardware Android back button works well in home and login pages. But in Blankpage when I press hardware Android back button app crashed.
This is output:

```
Can't find variable: popRoute
<unknown>
AppNavigator.js:1266:0
```

How can I fix it?

**Comment by SupriyaKalghatgi** [comment]
@aliajoudanian Native Starter Kit has been updated
Try the latest version and let me know if you still face the same issue

**Comment by aliajoudanian** [comment]
Thanks, It fixed.
