### ISSUE TITLE
CODEPUSH_KEY Error

### ISSUE THREAD

**Issue by sankar2389** [start-react/native-starter-kit#15]
CodePush Key should be denoted as

buildConfigField "String", "CODEPUSH_KEY", ' "codepush production key" '

**Comment by bobloblaws93** [comment]
Hey sankar, I'm still getting errors with this.
I have the following in my gradle:
buildConfigField "String", "CODEPUSH_KEY", ' "my key here" '

but I still get an error stating:

BuildConfig.java:14: error: unclosed character literal
  public static final String CODEPUSH_KEY = 'my key here';

where 'my key here' is the actual production key

Any help would be greatly appreciated

**Comment by bobloblaws93** [comment]
Nvm, Its ok i've solved it
for those who have my issue you have to enter an escape
so it would look like this:

buildConfigField "String", CODEPUSH_KEY, "\"PUT_YOUR_KEY_HERE \""

**Comment by sankar2389** [comment]
I just placed my Codepush key like this (used both single quotes & double quotes), 

buildConfigField "String", "CODEPUSH_KEY", ' "7e54654asdasdf5454654" '
