### ISSUE TITLE
Change page's transition

### ISSUE THREAD

**Issue by aliajoudanian** [start-react/native-starter-kit#16]
I couldn't find any option to change it.
Am I able to change the animation of routing between pages?

**Comment by SupriyaKalghatgi** [comment]
@aliajoudanian Native Starter Kit includes [React Native's Navigator](https://facebook.github.io/react-native/docs/navigator.html). Which by default has `PushFromRight` animation.
To customise this you can go through React Native docs

**Comment by SupriyaKalghatgi** [comment]
@aliajoudanian Did it work for you?

**Comment by aliajoudanian** [comment]
@SupriyaKalghatgi Yes, it worked. Thanks
