### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by juancabraal** [start-react/native-starter-kit#17]
I've downloaded the starter pack

And when I run the command
`npm install`

I receive these errors

`> NativeStarterKit@4.0.0 postinstall /Users/nedev/apps/native`
`> remotedev-debugger`

`PASS Inject RemoteDev monitor into React Native debugger.`
`npm ERR! Darwin 15.3.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"`
`npm ERR! node v4.4.0`
`npm ERR! npm  v2.14.20`
`npm ERR! code EPEERINVALID`

`npm ERR! peerinvalid The package react@15.2.1 does not satisfy its siblings' peerDependencies requirements!`
`npm ERR! peerinvalid Peer native-base@0.4.8 wants react@15.0.2 - 15.1.0`
`npm ERR! peerinvalid Peer react-native@0.27.2 wants react@15.1.0`
`npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/nedev/apps/native/npm-debug.log`

Can u help me fixing it?

**Comment by juancabraal** [comment]
I could fix all the installation bug

now I'm having this problem

> Application NativeStarterKit has not been registered. This is either due to require() error during initializtion or failure to call AppRegistery.registerComponent

How can I solve it?

**Comment by SupriyaKalghatgi** [comment]
@juancabraal Sorry for the inconvenience
Experimental code was pushed on to branch `master`.
You can now get started from branch `master`
