### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by johntom** [start-react/native-starter-kit#2]
Interested in your product (pro version) and decied to try the free sample. The following screen displays on genymotion.
![capture](https://cloud.githubusercontent.com/assets/1877376/12634500/0d2cb544-c548-11e5-99eb-e39544e26d0a.PNG)

**Comment by johntom** [comment]
![capture](https://cloud.githubusercontent.com/assets/1877376/12634515/3fb96782-c548-11e5-84f8-6f5752c29ff7.PNG)

**Comment by sanketsahu** [comment]
John, we are checking the issue.

We will get back to you.

**Comment by sankhadeeproy007** [comment]
Hi, run `react-native upgrade` and overwrite all the files it prompts you to overwrite. You should be good to go.

**Comment by johntom** [comment]
Hi,
Yes that fixed that problem..
1) Now when I login the menu and back options are missing.
2) I think the demo would show the logged in user and not just Hey There
Thanks,
John

**Comment by sankhadeeproy007** [comment]
We've already done that in the pro version and are thinking of implementing it here on the demo as well. But it's not high up on the priority list.

**Comment by johntom** [comment]
No problem, just a suggestion. I brought pro version. Working with it
tomorrow
