### ISSUE TITLE
unable to resolve module color in base-theme.js

### ISSUE THREAD

**Issue by mgenev** [start-react/native-starter-kit#22]
It crashes upon running.
![screen shot 2016-08-01 at 2 34 14 pm](https://cloud.githubusercontent.com/assets/3029803/17309727/0ad4e948-57f5-11e6-9183-ea9d1dc41f2e.png)

**Comment by SupriyaKalghatgi** [comment]
@mgenev I checked running the kit and its working fine
Try deleting `node_modules` and follow installation procedure again

**Comment by SupriyaKalghatgi** [comment]
@mgenev Did it work for you?

**Comment by anovafawzi** [comment]
I'm also found the similar problem with color module so I thought maybe I just put it in here as well. Already tried your suggestion to delete the node_modules and re-install it but no luck. This is the screenshot of my error when running on android emulator (I'm using Win 10 btw)

![image](https://cloud.githubusercontent.com/assets/4485792/17428101/fb2cb4d0-5b0f-11e6-8e14-32976fdf65c6.png)

Do you have any suggestion for this?

**Comment by SupriyaKalghatgi** [comment]
@anovafawzi Can you let me know adding `"color": "~0.11.1"` to your `package.json` and re-install node_modules?

**Comment by anovafawzi** [comment]
@SupriyaKalghatgi okay will let u know asap

**Comment by anovafawzi** [comment]
@SupriyaKalghatgi you're right, it lacks with color package (i just do the npm install once again without deleting the node_modules folder). it's running well now, thanks :+1:

**Comment by SupriyaKalghatgi** [comment]
@anovafawzi NSK includes `color` from [NativeBase](http://nativebase.io/)
I tried fresh installs many a times, but never faced this.

**Comment by SupriyaKalghatgi** [comment]
Fixed with [latest commit](https://github.com/start-react/native-starter-kit/commit/d475c0c0274120e367e89bf787a4b24fc6046152)
