### ISSUE TITLE
please update the reference packages

### ISSUE THREAD

**Issue by cbcye** [start-react/native-starter-kit#23]
RN version just 0.27 and Native Base version is 0.4.9 , the List component of Native Base can not support dynamic data source. i try to update all of modules but get a lot of error. i am worry to use this starter kit into my project.

**Comment by SupriyaKalghatgi** [comment]
@cbcye Its not just that we update NSK as soon as the new version of [NativeBase](http://nativebase.io) is released.
This kit is a demo version of our pro theme [Native Starter Pro](http://strapmobile.com/native-starter-pro/) and other themes as well. So it takes some time for us to keep our themes and NSK synchronized with NativeBase .
You can very soon find the new release of NSK.

**Comment by ghost** [comment]
+1

**Comment by basequatro** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
@cbcye @herve1976 @basequatro Fixed with [v5.0.0](https://github.com/start-react/native-starter-kit/releases/tag/v5.0.0)
