### ISSUE TITLE
[Question] License?

### ISSUE THREAD

**Issue by pitzcarraldo** [start-react/native-starter-kit#24]
Hi All.

I have a little question. What is the license of the repo?
Could I make commercial service with codes and resources of this project?
If could, is there any rules to use this for it.

Thanks.

**Comment by SupriyaKalghatgi** [comment]
@Pitzcarraldo The kit is updated with [License](https://github.com/start-react/native-starter-kit/blob/master/LICENSE).
You can check it and its commercially free to use.

**Comment by pitzcarraldo** [comment]
Great.
Thanks.
