### ISSUE TITLE
Unable to resolve module TextInputState

### ISSUE THREAD

**Issue by akhivicky** [start-react/native-starter-kit#25]
Unable to resolve module TextInputState from /Users/stplmacmini6/Desktop/native-starter-kit/node_modules/react/lib/NativeMethodsMixin.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/TextInputState and its parent directories.

I also follow the steps:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`

but did not fix. Also I have upgraded node.js and react-native with latest version.

**Comment by SupriyaKalghatgi** [comment]
@akhivicky Your console output says _Unable to find this module in its module map or any of the node_modules directories under_ **/Users/node_modules/TextInputState**

Whereas the module was to be searched under path **/Users/stplmacmini6/Desktop/native-starter-kit/node_modules/react/lib/NativeMethodsMixin.js**

So this is not an issue with NSK

Try restarting your system

**Comment by akhivicky** [comment]
I saw the TextInputState.js file is not found on path  /Users/stplmacmini6/Desktop/native-starter-kit/node_modules/react/lib/ but accessing from same directory and in new version of react 0.31.0 it has mapped in react-native/lib so rather using require('TextInputState') instead use require('react-native/lib/TextInputState'). Might be it is the issue.

**Comment by akhivicky** [comment]
Hey its solve my problem by replacing require('TextInputState') to require('react-native/lib/TextInputState') in node_modules/react/lib/NativeMethodsMixin.js

**Comment by SupriyaKalghatgi** [comment]
@akhivicky Seems that you are trying NSK with RN 0.31
NSK will be soon updated with RN 0.31
Issues regarding this would be welcome once NSK is updated

**Comment by Mentioum** [comment]
hi @SupriyaKalghatgi is there an ETA on the update to RN 0.31 / 32

**Comment by SupriyaKalghatgi** [comment]
@Mentioum yes. By this week

**Comment by henryw4k** [comment]
Hi, if we purchase the pro version, can we upgrade for free when you guys have RN 0.31/32 out?

**Comment by SupriyaKalghatgi** [comment]
@henryw4k @dsernst Yes
We provide our customers with git-access of Full version and Seed version.

**Comment by SupriyaKalghatgi** [comment]
@akhivicky @Mentioum @henryw4k @dsernst Fixed with [v5.0.0](https://github.com/start-react/native-starter-kit/releases/tag/v5.0.0)
