### ISSUE TITLE
Don‘t understand how ProgressBar imported

### ISSUE THREAD

**Issue by linonetwo** [start-react/native-starter-kit#26]
At [this line](https://github.com/start-react/native-starter-kit/blob/master/js/App.js#L10) it said: 

```
import ProgressBar from './components/loaders/ProgressBar';
```

However there are : 
ProgressBar.android.js
ProgressBar.ios.js
Spinner.android.js
Spinner.ios.js

I don't understand how these files are imported. I'm trying to use flowtype to do some type check, but now it will complain about `./components/loaders/ProgressBar Required module not found`

**Comment by linonetwo** [comment]
And where does the `Reducer`
at [here](https://github.com/start-react/native-starter-kit/blob/0411fad013eabe31813f8830ac0f53b5b61b8e09/js/AppNavigator.js#L47)
`const defaultReducer = Reducer(params);` comes from?

**Comment by himanshu-satija** [comment]
@linonetwo 
1. We have used the platform specific ProgressBar. So, if you write 

```
import ProgressBar from './components/loaders/ProgressBar';
```

ProgressBar will be imported from `ProgressBar.android.js` on an Android device and from `ProgressBar.ios.js` on an iOS device.
1. You can safely remove these lines.

```
const reducerCreate = params=>{
    const defaultReducer = Reducer(params);
    return (state, action)=>{
        var currentState = state;

        if(currentState){
            while (currentState.children){
                currentState = currentState.children[currentState.index]
            }
        }
        return defaultReducer(state, action);
    }
};
```

`reducerCreate` is not being used anywhere. We'll remove all the redundant code in next release.

**Comment by linonetwo** [comment]
Thank you , awesome work
