### ISSUE TITLE
README & rnpm

### ISSUE THREAD

**Issue by babakness** [start-react/native-starter-kit#27]
Hey guys, the readme says to run rnpm but you guys don't say to install it even though you mention installing things like node.

Maybe you guys can mention in system requirements. I did `npm install -g rnpm`

**Comment by SupriyaKalghatgi** [comment]
@babakness The ReadMe specifies only the version dependency for `node` and `npm`.
The ReadMe has been updated for [System Requirements](https://github.com/start-react/native-starter-kit#1-system-requirements) with other basic packages as well.
