### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by sibelius** [start-react/native-starter-kit#3]
https://rnplay.org/apps/vPqdqA is not working

requiring unknown module 'react-native-drawer'

**Comment by sankhadeeproy007** [comment]
Hello! We've had to take down the demo because rnplay wouldn't allow 3rd party modules. I've attached a gif in the desc. You can always clone/download and try it out.

**Comment by sibelius** [comment]
you should put an example on exponentjs

**Comment by sankhadeeproy007** [comment]
Yes, we've already published the full version in Google Play Store and are very soon going to publish it on App Store as well.
