### ISSUE TITLE
Unable to update font size of input field within inputgroup and placeholder color

### ISSUE THREAD

**Issue by amourya-systango** [start-react/native-starter-kit#30]
Base them properties does not update font size and placeholder color of input field even updating the property value of fontSizeBase, inputColorPlaceholder and iconFontSize

**Comment by SupriyaKalghatgi** [comment]
@amourya-systango This was a bug of NativeBase 0.4.9, which has been solved in its succedent release.
And also NSK will have the latest version of NativeBase (0.5.5) and React Native (0.31) very soon

**Comment by SupriyaKalghatgi** [comment]
@amourya-systango Fixed with [v5.0.0](https://github.com/start-react/native-starter-kit/releases/tag/v5.0.0)
