### ISSUE TITLE
Picker.item style don't work

### ISSUE THREAD

**Issue by basequatro** [start-react/native-starter-kit#31]
itemStyle={{fontSize: 25, color: 'red', textAlign: 'left', fontWeight: 'bold'}}
Item labels are white on a white background for IOS
How i can style picker item in native starter kit?

**Comment by SupriyaKalghatgi** [comment]
@basequatro
Did you check this on NativeBase?

**Comment by basequatro** [comment]
@SupriyaKalghatgi Yes, they've said on a closed issue that styling code is the same as Picker for react native.

**Comment by SupriyaKalghatgi** [comment]
@basequatro Check [Issue #122](https://github.com/GeekyAnts/NativeBase/issues/122)

**Comment by sankhadeeproy007** [comment]
Hi, itemStyle is not supported yet by nativeBase.

**Comment by dinithminura** [comment]
@sankhadeeproy007,  No other option to style picker item in nativeBase? One time I have change theme text color to  style picker item and change other particular text colors.

**Comment by shivrajkumar** [comment]
Picker Item can be styled with `itemStyle` and `itemTextStyle` with NativeBase v2.x

**Comment by Johncy1997** [comment]
![pickeritem](https://user-images.githubusercontent.com/25324938/46199640-2feff600-c32d-11e8-8ecf-6f098a17eb32.png)


In my case, I want to set a radio button for selectedItem. Someone tell me what should i do for this?
