### ISSUE TITLE
how do you use fontawesome icons?

### ISSUE THREAD

**Issue by dsernst** [start-react/native-starter-kit#32]
How do you use fontawesome icons? It is unclear from the documentation. And the code is very misdirected.

**Comment by dsernst** [comment]
But the documentation says this icon set pulls in FontAwesome.

**Comment by Proxiweb** [comment]
I think you have to set iconFamily to "FontAwesome"  in /themes/base-theme.js ...

**Comment by SupriyaKalghatgi** [comment]
@dsernst @Proxiweb Yes, you should set the iconFamily in `base-theme.js`
Refer NativeBase issue for same [#148](https://github.com/GeekyAnts/NativeBase/issues/148)
