### ISSUE TITLE
RCTTextView is not a descendant of RCTShadowView

### ISSUE THREAD

**Issue by alfondotnet** [start-react/native-starter-kit#33]
This just came up when I fire up the simulator of a fresh cloned project. 
<img width="353" alt="screen shot 2016-09-11 at 7 31 46 pm" src="https://cloud.githubusercontent.com/assets/3578008/18422876/9555f70e-7854-11e6-96d9-bae95ce9c57c.png">

Someone has a clue of what can be happening?.

Thanks!

**Comment by SupriyaKalghatgi** [comment]
@alfonsoperez This is an issue with React Native 0.31 which has been fixed in React Native 0.32.

**Comment by alfondotnet** [comment]
Oh, yeah I see, thanks, closing.
