### ISSUE TITLE
State mutation detected inside a dispatch, in the path `route.routes.1`

### ISSUE THREAD

**Issue by rwngallego** [start-react/native-starter-kit#35]
Hi! I've installed [redux-immutable-state-invariant](https://github.com/leoasis/redux-immutable-state-invariant) and it has detected a state mutation here: https://github.com/start-react/native-starter-kit/blob/5f37096/js/reducers/route.js#L25-L34

It would be healthy to the project to add this detector in order to don't mutate state when using redux. I've added a PR in order to add state mutation checks. **However we need to remove all the state mutations we have so far because they are pretty dangerous.**

PR: https://github.com/start-react/native-starter-kit/pull/34

![state_mutation](https://cloud.githubusercontent.com/assets/691521/18609797/4a9b3ab4-7cd0-11e6-83de-8af2c1a1edfc.png)

**Comment by SupriyaKalghatgi** [comment]
Merged request
