### ISSUE TITLE
iOS UN/PW input focus errors out with "view is not a descendant of RCTShadowView"

### ISSUE THREAD

**Issue by darron-haworth** [start-react/native-starter-kit#37]
Pulled down the latest react-native-starter-kit, looks great but when I place focus in the username or password fields on the login component I get the following error:

`view <RCTShadowView: 0x60000001d0590; viewName: RCTTextField; reactTag: 24; frame: {{323, 40}}> (tag $24) is not a descendant of <RCTShadowView: 0x6180001d0a40; viewName: RCTView; reactTag: 37; frame: {{10,30}, {290, 79}}> (tag #38)`

This does not happen on Android, it happens on iPhone 6, works fine on iPhone 7 plus.

The only article I could find related is this: http://stackoverflow.com/questions/37788069/rcttextfield-is-not-a-descendant-of-rctshadowview-error but I don't seem to be able to resolve issue

![simulator screen shot sep 18 2016 2 42 02 pm](https://cloud.githubusercontent.com/assets/9342747/18619340/d0cde2b0-7dae-11e6-8b0a-c0cd8e5470db.png)

**Comment by SupriyaKalghatgi** [comment]
@darron-haworth Refer this #33

**Comment by darron-haworth** [comment]
I was able to resolve my issues by upgrading to react 15.3.1, react-native 0.33.0, react-native-keyboard-aware-scrollview 2.0.
