### ISSUE TITLE
Codepush Key, Portrait, Readme, Background

### ISSUE THREAD

**Issue by basequatro** [start-react/native-starter-kit#39]
Hi There!

Any plans to make your framework/themes compatible with portrait?
![screen shot 2016-09-28 at 3 12 36 pm](https://cloud.githubusercontent.com/assets/2417603/18926436/30e42416-858e-11e6-8cc0-7959ffc36edc.png)

Also, could please elaborate how we can add the codepush keys on IOS? 
![screen shot 2016-09-28 at 3 13 48 pm](https://cloud.githubusercontent.com/assets/2417603/18926437/30e68594-858e-11e6-9043-aae9869b1d93.png)

Missing some details here for begginers:
Add the codepush production key in place of Release key
Add the codepush staging key in place of Debug key

Is there any problem with images or the background was changed to white in this new version?

**Comment by SupriyaKalghatgi** [comment]
@basequatro For detailed implementation of CodePush, you can refer its [ReadMe](https://github.com/Microsoft/react-native-code-push)
You can follow steps mentioned here for [iOS key deployment](https://github.com/Microsoft/react-native-code-push#ios)

There are no issues with background images. NSK has been updated with pure NativeBase components with least usage of external styles.

**Comment by basequatro** [comment]
I can't compile this project for Android.
Any idea what i've missed?

![screen shot 2016-09-29 at 10 50 42 pm](https://cloud.githubusercontent.com/assets/2417603/18978201/4187b0ee-8697-11e6-87a9-73c5e460472c.png)

**Comment by SupriyaKalghatgi** [comment]
@basequatro Can you list down the steps you followed to set up NSK for Android?

**Comment by basequatro** [comment]
1. Made it work with IOS first.
2. Link with with react-native link

Set in build.gradle app

```
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            buildConfigField "String", "CODEPUSH_KEY", "XXXX"
        }
        debug {
            buildConfigField "String", "CODEPUSH_KEY", "YYYY"
        }
```
1. Set in java file

```
new CodePush("XXXX", MainApplication.this, BuildConfig.DEBUG)
```

**Comment by basequatro** [comment]
This happens when i set debug key.

```
        debug {
            buildConfigField "String", "CODEPUSH_KEY", "MYSTAGINGKEY"
        }
```

If i remove debug { ...} the project builds fine

![screen shot 2016-09-30 at 4 06 03 am](https://cloud.githubusercontent.com/assets/2417603/18983464/4f9bcb1c-86c3-11e6-9cf5-6ced0885f00a.png)

```
  // Fields from build type: debug
  public static final String CODEPUSH_KEY = MYSTAGINGKEY;
```

**Comment by basequatro** [comment]
I\ve added also this to strings.xml

```
<string moduleConfig="true" name="reactNativeCodePush_androidDeploymentKey">MYPRODKEY</string>
```

**Comment by SupriyaKalghatgi** [comment]
@basequatro Its very simple
1. `react-native link react-native-code-push`
2. Enter codepush keys
This automatically adds key to `android/app/src/main/res/values/strings.xml`
Also no need of adding keys in `MainApplication.java`
3. Go to `android/app/build.gradle` and add this

```
buildTypes {
    debug {
         buildConfigField "String", "CODEPUSH_KEY", '"codepush_staging_key"'
    }
    release {
        buildConfigField "String", "CODEPUSH_KEY", '"codepush_production_key"'
    }
}
```

**Comment by SupriyaKalghatgi** [comment]
@basequatro Still facing issues?

Check the latest release of NSK
