### ISSUE TITLE
the native-starter-kit is not working 

### ISSUE THREAD

**Issue by sumanbogati** [start-react/native-starter-kit#4]
I have followed your instructions to install "native-starter key" in my window7 computer, but after  started the project by 'react-native start', the error(**Module AppRegistry is not registered callable module**) is coming as shown in attached image.

Can you please tell me why this is happening ?

![error_module](https://cloud.githubusercontent.com/assets/1753974/15272589/7a4870c0-1a9b-11e6-82e5-117ca24f8be6.png)

**Comment by sankhadeeproy007** [comment]
This is not a problem with `native-starter-kit` and more of a problem with react-native and windows itself. You can go through these links and try out the solutions given there.
http://stackoverflow.com/questions/34969858/react-native-module-appregistry-is-not-a-registered-callable-module
https://github.com/jhabdas/react-native-webpack-starter-kit/issues/58

**Comment by ghost** [comment]
Oddly the SO site is down today. Those looking at my kit please note my software is not paid, it is open source, and the error pictured in this issue here is likely not specific to Windows or OS X.

**Comment by sumanbogati** [comment]
The attached error was not origin from demo app.
