### ISSUE TITLE
How to run starter kit on actual iOS and Android devices

### ISSUE THREAD

**Issue by cpalanzo** [start-react/native-starter-kit#40]
Okay... I've successfully installed and ran the starter kit in my iOS simulator (XCODE 8.0) but I would like to run it on actual devices connected to my iMAC.

I tried opening XCODE and loading the project and running it directly - but get compilation and signing errors. 

Is there a written guide for this?

**Comment by SupriyaKalghatgi** [comment]
@cpalanzo You can refer SO for such generic questions

**Comment by cpalanzo** [comment]
I looked in the documentation and it was not clear.The Normal path of opening the XCODE project and compiling it did not work.There were websocket compile issues - AND signing issues. 
This would be a logical next step for any developer - running on the simulator is good - but running on real devices is better.
Please reference exact links - I'm sure others will have this problem.
And yes, I know XCODE is a PAIN to work with. -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: SupriyaKalghatgi <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, September 29, 2016 8:37 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

@cpalanzo You can refer SO for such generic questions—

**Comment by SupriyaKalghatgi** [comment]
@cpalanzo Did you try this?
[Run Apps on iPhone](http://stackoverflow.com/questions/30727099/how-to-run-apps-on-iphone-ipad-using-xcode-7-without-enrolling-to-apples-develo)

**Comment by cpalanzo** [comment]
Yes.. but I will do it again and record/screen-capture any errors.I've already developed and released apps to both the App Store and Google play .. but maybe something with XCODE 8 is configured wrong.
Thanks, -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: SupriyaKalghatgi <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, September 29, 2016 10:20 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

@cpalanzo Did you try this?
Run Apps on iPhone—

**Comment by cpalanzo** [comment]
Okay... I ran a more complete trial this morning with XCODE - and have found TWO sets of problems. 
1 - Two Web Socket Compile errors in the code
then after I comment out the offending errors
2 - Signing Identify problems I can't figure out

First I ran react-native from the terminal - it all worked find as this screenshot shows:
![screenshot 2016-09-30 07 09 06](https://cloud.githubusercontent.com/assets/9503630/18990184/47acd3cc-86de-11e6-92f7-8ca1de527f6c.png)

I closed everything and opened XCODE 8.0 directly - I get TWO Web Socket build errors as shown in two screens below:
![screenshot 2016-09-30 07 10 06](https://cloud.githubusercontent.com/assets/9503630/18990206/6820fc32-86de-11e6-8e7c-337d3439722b.png)

![screenshot 2016-09-30 07 10 15](https://cloud.githubusercontent.com/assets/9503630/18990224/7d44e5c4-86de-11e6-90ae-bdd269b6aca9.png)

I simply commented out the two offending lines with //... then I try and build and get a signing error as shown:
![screenshot 2016-09-30 07 14 14](https://cloud.githubusercontent.com/assets/9503630/18990243/979143aa-86de-11e6-9ade-ee518cc87d4f.png)

I try two (actually more) combinations of signing options - but could NOT find one that works. Note: I have an active developer account. Not sure what is going on here. Detail at last screenshot.
![screenshot 2016-09-30 07 17 23](https://cloud.githubusercontent.com/assets/9503630/18990282/d94130f8-86de-11e6-8b71-19d43ceed76f.png)

![screenshot 2016-09-30 07 15 07](https://cloud.githubusercontent.com/assets/9503630/18990270/c3c23074-86de-11e6-916f-6bcfaf511836.png)

![screenshot 2016-09-30 07 17 13](https://cloud.githubusercontent.com/assets/9503630/18990273/cab63506-86de-11e6-91af-77cdade68dc3.png)

**Comment by cpalanzo** [comment]
I posted additional details / with screenshots - there are issues to running in XCODE.. please take a look on Github., view it on GitHub,
 -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: SupriyaKalghatgi <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, September 29, 2016 10:20 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

@cpalanzo Did you try this?
Run Apps on iPhone—

**Comment by cpalanzo** [comment]
Where does this stand? Please help me out so I can move forward with the evaluation.Charlie -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: SupriyaKalghatgi <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, September 29, 2016 10:20 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

@cpalanzo Did you try this?
Run Apps on iPhone—

**Comment by sanketsahu** [comment]
From the docs:
https://facebook.github.io/react-native/docs/running-on-device-ios.html

**Comment by cpalanzo** [comment]
You keep pointing me back to the docs.. I've looked. I will look again but I'm dealing with:1. Websocket errors .. and2. Signing errors
I've built multiple iOS apps and this is the first one that is having problems. How can I evaluate your packages if I can't run them on devices - only in simulators?
 -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: Kumar Sanket (aka Sanket Sahu) <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Tuesday, October 4, 2016 4:45 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

From the docs:
https://facebook.github.io/react-native/docs/running-on-device-ios.html—

**Comment by SupriyaKalghatgi** [comment]
@cpalanzo In Xcode 8.0, you need to SignIn for tests section also.
Check this
![screen shot 2016-10-13 at 1 20 51 pm](https://cloud.githubusercontent.com/assets/13464885/19340769/2903f576-9148-11e6-84a5-3dda0f54019f.png)
Let me know if this solves your problem.

**Comment by cpalanzo** [comment]
Finally!It didn't work at first - that would be TOO easy for iOS.I had to use automated settings for the NativeStarterKit target ... and manual settings for NativeStarterKitTests.
XCODE and the iOS development systems GUARANTEE job security for anyone who understands their complexity - just being able to figure out build settings seems like a reasonable basis for a consultancy.Imagine - getting code to run on a target is harder than writing the code in the first place? Only APPLE.
That said - since you have a decent react native starter kit - I think it would be in your best interests to capture and post the complete method of launching iOS and running on real iOS products. Simulation is good - but as soon as that runs any reasonable person will want to see the starter kit on live hardware.
Charlie -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: SupriyaKalghatgi <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Thursday, October 13, 2016 3:53 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

@cpalanzo In Xcode 8.0, you need to SignIn for tests section also.
Check this

Let me know if this solves your problem.—

**Comment by SupriyaKalghatgi** [comment]
@cpalanzo Are you still facing issue?

**Comment by cpalanzo** [comment]
No - as in my comments above your solution worked - just configuring XCODE is a major headache.Thanks,c -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

```
  From: SupriyaKalghatgi <notifications@github.com>
```

 To: start-react/native-starter-kit native-starter-kit@noreply.github.com 
Cc: Charlie Palanzo palanzo@yahoo.com; Mention mention@noreply.github.com
 Sent: Friday, November 11, 2016 12:39 AM
 Subject: Re: [start-react/native-starter-kit] How to run starter kit on actual iOS and Android devices (#40)

@cpalanzo Are you still facing issue?—

**Comment by SupriyaKalghatgi** [comment]
@cpalanzo Sounds good

Do check the latest release of NSK
