### ISSUE TITLE
how do I start it as it failes

### ISSUE THREAD

**Issue by tzookb** [start-react/native-starter-kit#41]
when I do 

```
react-native run-ios
```

*\* BUILD FAILED **

The following build commands failed:
    CompileC /Users/tzookb/Downloads/native-starter-kit-master/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NativeStarterKit.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by SupriyaKalghatgi** [comment]
@tzookb This is not an issue of NSK
Looks like you are on Xcode 8
Try deleting `Custom Compiler Flags` through Xcode

**Comment by tzookb** [comment]
Thanks!
Any idea where I can find it?
Not an xcode expert...

**Comment by SupriyaKalghatgi** [comment]
@tzookb You can check it in issues of RN [#8584](https://github.com/facebook/react-native/issues/8584)

**Comment by SupriyaKalghatgi** [comment]
@tzookb Could you build NSK successfully?

**Comment by tzookb** [comment]
@SupriyaKalghatgi thanks it worked!

**Comment by oldo** [comment]
Wow, I wasted a lot of time before I found this thread...!
