### ISSUE TITLE
Logout Animation

### ISSUE THREAD

**Issue by basequatro** [start-react/native-starter-kit#42]
I'm having problem when logout, the animation its getting stuck between transition.
![nsk-logout-lag-export](https://cloud.githubusercontent.com/assets/2417603/18978489/f94ec620-8699-11e6-868a-2239230fc24a.gif)

**Comment by SupriyaKalghatgi** [comment]
@basequatro Can you pull the latest and check again?

**Comment by SupriyaKalghatgi** [comment]
@basequatro Fixed with latest push
