### ISSUE TITLE
Delay using Picker

### ISSUE THREAD

**Issue by basequatro** [start-react/native-starter-kit#44]
I'm having issue when opening the modal from picker component.
There's a big delay until the modal is shown.

This is not happening with nativebase and awesome project.

**Comment by sanketsahu** [comment]
@basequatro Please raise the issue in NativeBase repo if it is related to that.

Some code snippet would be appreciated and it will help us looking into the problem and recreating it.

**Comment by basequatro** [comment]
@sanketsahusoft This issue is only with NSK. Native base and awesome project is working fine.
