### ISSUE TITLE
Failed at the NativeStarterKit

### ISSUE THREAD

**Issue by MattHartz** [start-react/native-starter-kit#47]
Hi,

I just recently did a fresh install for React-native on my windows machine and am following the steps to install the native-starter-kit kit for a fresh project.  When running npm install, I am receiving an error of "Failed at the NativeStarterKit@5.2.0 postinstall script 'remotedev-debugger && sh .add-pre-commit-hook'.  

It states to ensure i have the latest version of node.js and npm which I do.  

Any ideas what the issue is?

P.S. Also because of this if i try to link I get errors such as "Cannot read property '1' of null" in postlink.js and a few other errors.

Thanks!

**Comment by SupriyaKalghatgi** [comment]
@MattHartz Can you please share screenshot of your console for same?

**Comment by MattHartz** [comment]
Hi @SupriyaKalghatgi, I'll get it to you soon.

**Comment by MattHartz** [comment]
![image](https://cloud.githubusercontent.com/assets/16110147/20086991/70cbc862-a529-11e6-9bda-49492c536cf2.png)

Is it related to sh failing? If so, do you know the best way to get sh command?

**Comment by dima11221122** [comment]
+1

**Comment by dima11221122** [comment]
i run `npm install` in cygwin and it solve problem.

**Comment by MattHartz** [comment]
@dima11221122 I'll try that when i get home. Thanks!

**Comment by SupriyaKalghatgi** [comment]
Yes i agree with @dima11221122 .

@MattHartz This should be helpful to you.

**Comment by SupriyaKalghatgi** [comment]
@MattHartz Any results for this?

**Comment by MattHartz** [comment]
Sorry I bailed on it and built my project from scratch. :)

**Comment by ts-ign0re** [comment]
+1

**Comment by SupriyaKalghatgi** [comment]
@tronin Please pull the latest from `master` and try again
