### ISSUE TITLE
Unfortunately NativeStarter has stopped.

### ISSUE THREAD

**Issue by Netsoro** [start-react/native-starter-kit#5]
when i build react native starter app, on  debug mode everythings work fine, but on release the app is unable to start, i always have this error  Unfortunately NativeStarter has stopped.

![capture du 2016-05-16 12-33-34](https://cloud.githubusercontent.com/assets/1739996/15287932/badbe0f6-1b66-11e6-9f9a-24faf859912d.png)

react native 0.25.1 
ubuntu 15.04

Any hint please.

**Comment by sankhadeeproy007** [comment]
Have you checked the adb logs? 
https://facebook.github.io/react-native/docs/debugging.html

**Comment by Netsoro** [comment]
@sankhadeeproy007 thank you for your responsive, english is not my first language so :) , i get  this E/ReactNativeJS(18175): undefined is not an object (evaluating 'p.propTypes.style')
E/ReactNativeJS(18175): Module AppRegistry is not a registered callable module.

**Comment by Netsoro** [comment]
This issue is discussed here   [Android]Release crash "s.propTypes.style" #5655

**Comment by sankhadeeproy007** [comment]
We made a signed version of our app from the same template. So it's probably some code from your side which is causing this. Did you try out the solutions from the RN thread?

**Comment by Netsoro** [comment]
@sankhadeeproy007   By disabling proguard everythings  works fine,  
def enableProguardInReleaseBuilds = false
Thks,
