### ISSUE TITLE
react-native link problem

### ISSUE THREAD

**Issue by thiagoterleski** [start-react/native-starter-kit#52]
HI! anyone can help me with this error?

`D:\_DEV\_Labs\ReactNative\native-starter-kit>react-native link
? What is your CodePush deployment key for Android (hit <ENTER> to ignore) _gi-TBhZ56viRsyUMe6kZPDgcSVV4yodWNPWf
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
D:\_DEV\_Labs\ReactNative\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (D:\_DEV\_Labs\ReactNative\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_DEV\_Labs\ReactNative\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:570:32)
D:\_DEV\_Labs\ReactNative\native-starter-kit\node_modules\react-native\local-cli\core\makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (D:/_DEV/_Labs/ReactNative/native-starter-kit/node_modules/react-native/local-cli/core/makeCommand.js:19:15)`

react-native-cli: 1.2.0
react-native: 0.35.0
npm: 3.10.9

**Comment by SupriyaKalghatgi** [comment]
@thiagoterleski Try deleting `node_modules` and install again

**Comment by gouravsood** [comment]
@SupriyaKalghatgi  I have the same problem. Tried removing the `node_modules` and still the same error:

$ react-native link
? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
<>\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\ios\postlink.js:26:96)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<>\native-starter-kit\node_modules\react-native-code-push\scripts\postlink\run.js:1:63)
    at Module._compile (module.js:570:32)
<>\native-starter-kit\node_modules\react-native\local-cli\core\makeCommand.js:19
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (<>/native-starter-kit/node_modules/react-native/local-cli/core/makeCommand.js:19:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by SupriyaKalghatgi** [comment]
@thiagoterleski @gouravsood I tried with a fresh install of NSK. 
Goes fine by my side.
You can check CodePush Issue [#586](https://github.com/Microsoft/react-native-code-push/issues/586)

**Comment by SupriyaKalghatgi** [comment]
@thiagoterleski @gouravsood Could you build successfully?

**Comment by thiagoterleski** [comment]
Same error :-(

I removed all node_modules and reinstall, but nothing works..

**Comment by SupriyaKalghatgi** [comment]
@thiagoterleski Check with this [#586](https://github.com/Microsoft/react-native-code-push/issues/586)

If nothing works, then last option left is to link CodePush manually

**Comment by gouravsood** [comment]
@thiagoterleski @SupriyaKalghatgi as suggested in https://github.com/Microsoft/react-native-code-push/issues/586 I have upgraded the version of codePush to 1.16.0-beta ("react-native-code-push": "^1.16.0-beta") and has removed the error. 

I can't see the same error but the process in command prompt is hanged. Its not completing and hanged at `Assets have been successfully linked to your project`. Not sure if this means task completion.

? What is your CodePush deployment key for Android (hit <ENTER> to ignore)
rnpm-install info Linking react-native-code-push android dependency
rnpm-install info Android module react-native-code-push has been successfully linked
rnpm-install info iOS module react-native-code-push is already linked
"CodePush.h" header already imported.
"jsCodeLocation" already pointing to "[CodePush bundleURL]".
"CodePushDeploymentKey" already specified in the plist file.
"getJSBundleFile" is already overridden
"codepush.gradle" is already linked in the build definition
rnpm-install info Linking react-native-vector-icons android dependency
rnpm-install info Android module react-native-vector-icons has been successfully linked
rnpm-install info iOS module react-native-vector-icons is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project

**Comment by SupriyaKalghatgi** [comment]
@gouravsood This seems to be linked successfully
Try to simulate now

**Comment by SupriyaKalghatgi** [comment]
@gouravsood Did you got the kit running?

**Comment by TheRealJAG** [comment]
Just to be clear, the fix for this issue is to open package.json and modify 

`"react-native-code-push": "1.15.0-beta",`

to 

`"react-native-code-push": "1.16.0-beta",`

I no longer get the error.

**Comment by rashmimhatre100** [comment]
my package.json does not have react-native-code-push. Any other solution?

**Comment by GeekRishabh** [comment]
@rashmimhatre100 You can use `reactnativeseed.com`

**Comment by geekrishabh** [comment]
@rashmimhatre100 You can use `https://reactnativeseed.com/` starter kit.
