### ISSUE TITLE
version issue 0.35.0 to 0.36.0

### ISSUE THREAD

**Issue by txs** [start-react/native-starter-kit#54]
I was npm installing the package, but the dependcies change to 0.36.0

so do you need to change the package version?

**Comment by SupriyaKalghatgi** [comment]
@txs That works fine.
The kit will be updated in a week or so with latest of RN and NB.
You are free to update the `package.json`
- If you want to work with RN < 0.38 then you should go for NB < 0.5.16
- For RN >= 0.38, NB 0.5.18 is compatible
