### ISSUE TITLE
Requiring unknown module: 'react-native/Libraries/Renderer/src/renderers/native/ReactNativePropRegistry'

### ISSUE THREAD

**Issue by alexicum** [start-react/native-starter-kit#55]
It's fixed in NativeBase 0.5.18: [#328](https://github.com/GeekyAnts/NativeBase/issues/328)

But native-starter-kit dependencies referencing NativeBase v "0.5.11"
and RN 0.35.0

Is it possible to upgrade to NativeBase 0.5.11 and RN 0.38.0 ?

**Comment by alexicum** [comment]
Fixed for now by replacing
`import ReactNativePropRegistry from 'react-native/Libraries/Renderer/src/renderers/native`/ReactNativePropRegistry';
by:
`import ReactNativePropRegistry from 'react\lib\ReactNativePropRegistry';`
in:
node_modules\react-native-easy-grid\Utils\computeProps.js

**Comment by SupriyaKalghatgi** [comment]
@alexicum If you want to work with RN < 0.38 then you should go for NB < 0.5.16
For RN >= 0.38, NB 0.5.18 is compatible

**Comment by alexicum** [comment]
@SupriyaKalghatgi I mean what is the reason that native-starter-kit is not updated to last versions
[NativeBase "0.5.11"](https://github.com/start-react/native-starter-kit/blob/master/package.json#L15) to 0.5.18 
and
[RN 0.35.0](https://github.com/start-react/native-starter-kit/blob/master/package.json#L17) to 0.38.0 ?

I did it and it works.

**Comment by alexicum** [comment]
> [The kit will be updated in a week or so with latest of RN and NB.](https://github.com/start-react/native-starter-kit/issues/54#issuecomment-264095840)

**Comment by SupriyaKalghatgi** [comment]
@alexicum  Its not just that we update NSK as soon as the new version of [NativeBase](http://nativebase.io) of RN is released.
This kit is a demo version of our pro theme [Native Starter Pro](http://strapmobile.com/native-starter-pro/). Also all other themes at **[StrapMobile](https://strapmobile.com/)** as well. So it takes some time for us to keep all our themes and NSK synchronized with NativeBase and RN .
You can very soon find the new release of NSK.
