### ISSUE TITLE
Pressing back button on Android causes no key defined error 

### ISSUE THREAD

**Issue by RyamBaCo** [start-react/native-starter-kit#56]
After Logging in and pressing one of the lines in the home screen I navigate to the blank page. When pressing the (physical) back button of my Android device the App crashes as no key is defined.

Happens in AppNavigator.js in
`this.props.popRoute(this.props.navigation.key); `(line 45)

I fixed it by
changing
`popRoute: () => dispatch(popRoute()),` (line 135)
to
`popRoute: key => dispatch(popRoute(key)),`

**Comment by SupriyaKalghatgi** [comment]
@RyamBaCo Fixed
