### ISSUE TITLE
Rename project!

### ISSUE THREAD

**Issue by shukerullah** [start-react/native-starter-kit#60]
What is better way to rename project directory and android package?

**Comment by SupriyaKalghatgi** [comment]
Follow this link to the docs of [Native Starter Pro](https://strapmobile.com/docs/native-starter-pro/master) to [rename app](https://strapmobile.com/docs/native-starter-pro/v5.2.0/guide/customize)

**Comment by shukerullah** [comment]
Thanks @SupriyaKalghatgi
