### ISSUE TITLE
Does the Drawer has Transitions?

### ISSUE THREAD

**Issue by Steviey** [start-react/native-starter-kit#62]
I get no transitions while using the drawer. Is it currently not implemented?

**Comment by SupriyaKalghatgi** [comment]
@Steviey Sorry for no updates
Can you please check the latest of Native Starter Kit for this?

**Comment by SupriyaKalghatgi** [comment]
This repo is deprecated
Please check [ReactNativeSeed.com](https://reactnativeseed.com/)
