### ISSUE TITLE
New Clone Error: View has no propType for native prop RCTView.aspectRatio

### ISSUE THREAD

**Issue by osolano** [start-react/native-starter-kit#66]
Hello,

I just cloned this project today and followed the getting started instructions exactly, and then ran the app using 
```react-native run-ios```

and get this error

![image](https://cloud.githubusercontent.com/assets/280426/22839490/791b2f5e-ef7e-11e6-97fc-79adeaaa346d.png)

**Comment by SupriyaKalghatgi** [comment]
@osolano Works fine for me on fresh clone

**Comment by osolano** [comment]
It's been a couple days since I ran this from clone and my environment has changed since then. Tested this today and everything looks good. Closing thanks!
