### ISSUE TITLE
Application NativeStarterKit has not been registered.

### ISSUE THREAD

**Issue by Morriz** [start-react/native-starter-kit#69]
I get this error after following the setup instructions":

'''Application NativeStarterKit has not been registered. This is either due to require () error during initializtion or failure to call AppRegistery.'''

I am on 5.3.0

**Comment by marcpechaitis** [comment]
@Morriz did you have another app running before you tried running NativeStarterKit?  I have had this happen to me in the past.  Try closing terminal and restart your simulator and try again, that's what worked for me.

**Comment by SupriyaKalghatgi** [comment]
@Morriz This happens if you faced an unsuccessful try for renaming the app
Or if any other project is running its packager.
You can terminate all the process from your terminal and try again
