### ISSUE TITLE
Padding problems on Android

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [start-react/native-starter-kit#7]
Hi, I would like to know if your product only targets iOS apps or if you support Android as well.
I'm asking this because I noticed that the widgets on Android are a little bit weird (look at the AppBar and the Button)
![starter](https://cloud.githubusercontent.com/assets/12840136/15630352/2a6812fe-250e-11e6-83c0-08efb1821afd.png)

I know its just a simple padding problem but since I will be buying your product (pro version) I would like to know if it's target for Android too

**Comment by rafaelcorreiapoli** [comment]
Besides, I'm getting some warning about deprecated methods
![deprecated](https://cloud.githubusercontent.com/assets/12840136/15630371/9e9e4ada-250e-11e6-9705-cde1d87b9f2a.png)

**Comment by sanketsahu** [comment]
@rafaelcorreiapoli It supoorts both Android and iOS, it has been fixed in the pro version. The free version will be updated next.

**Comment by rafaelcorreiapoli** [comment]
Hello @sanketsahusoft, I bought the pro version of starter kit
everything was fine until I noticed that it is using an outdated version of react native
I tried to update the react native version but the code was not compatible with newest versions. I like to use the latest versions to keep my software up to date with bug fixes and new features.
I would like to know if you plan on upgrading the code to use and updated version of react native. If you are not going to, then I've just lost 50$
Thanks!

**Comment by sanketsahu** [comment]
@rafaelcorreiapoli We are going to have continued support. We are launching Native Starter Pro with Redux and Native Base using React 0.25 this week (June 3rd). React Native is getting updated so fast that it's really difficult to keep a track of their pace, even the dependencies keep failing all the time. We are trying our best!

**Comment by rafaelcorreiapoli** [comment]
Hi @sanketsahusoft, is it released already ?

**Comment by sankhadeeproy007** [comment]
Hi @rafaelcorreiapoli, we've completed development and are currently in the process of refining the rough edges in our app. You'll be sent a download link for the new update tomorrow.

**Comment by rafaelcorreiapoli** [comment]
Thank you

**Comment by sankhadeeproy007** [comment]
@rafaelcorreiapoli We've decided to ship with 0.26 instead. Hence the delay. Thanks for the patience.

**Comment by sudharsan1988** [comment]
@sankhadeeproy007 I tried with 0.26 and getting an error(undefined is not an object(evaluating 'screenPhysicalPixels.width'). I hope, it will be fixed in the updated version. Any idea, when it's going to be available?

**Comment by SupriyaKalghatgi** [comment]
@rafaelcorreiapoli [Native Starter Pro](http://strapmobile.com/native-starter-pro/) v3.0 is released with [React Native](https://facebook.github.io/react-native/docs/getting-started.html) 0.26.2 + [NativeBase](http://nativebase.io/docs/v0.4.6/) 0.4.6 + [Redux](http://redux.js.org/) + [CodePush](https://github.com/Microsoft/react-native-code-push) + [React Native Navigator](https://facebook.github.io/react-native/docs/navigator.html).
Check the [docs](http://strapmobile.com/docs/native-starter-pro/v3.0/) for complete details.
We have updated the [Native Starter Kit](https://github.com/start-react/native-starter-kit) for same.

**Comment by SupriyaKalghatgi** [comment]
@rafaelcorreiapoli @sudharsan1988 Fixed with [v5.0.0](https://github.com/start-react/native-starter-kit/releases/tag/v5.0.0)
