### ISSUE TITLE
Native base 2.0

### ISSUE THREAD

**Issue by acamenhas** [start-react/native-starter-kit#72]
Hi,

I'll be interesting to have native base 2.0 by default on this starter kit.

For when?

Regards

**Comment by SupriyaKalghatgi** [comment]
@acamenhas Yes you can expect it in a couple of days.

**Comment by acamenhas** [comment]
Hope that it doesn't take too long.

**Comment by sotomaque1** [comment]
I've got a question. If i try rendering a separator in the home view I get a red screen saying error expected string etc., Could this be because separator is maybe from native base 2.0 and this isn't?

**Comment by sotomaque1** [comment]
https://github.com/start-react/native-starter-kit/issues/78

**Comment by SupriyaKalghatgi** [comment]
@acamenhas @sotomaque1 NSK updated with RN 0.41 and NB 2.0
