### ISSUE TITLE
how do we pass the API data from one component to another?

### ISSUE THREAD

**Issue by piyush565** [start-react/native-starter-kit#77]
Issue is How to pass the list item data we are fetching in a page B to Page C. not able to figure out how to bind and send data because page navigation is going on using app navigator.
it would be great help if you suggest with code.

Thanks in advance

**Comment by janzenz** [comment]
you can use [Redux](http://redux.js.org/) for passing data from scene to scene just make sure it's not a sensitive data that you're passing because it's in plain text.
