### ISSUE TITLE
element type is invalid. help PLEASE

### ISSUE THREAD

**Issue by sotomaque** [start-react/native-starter-kit#78]
when modifying the home component to display anything but the grid, like a list item for example, i get a red error screen. 
<img width="1280" alt="screen shot 2017-03-05 at 2 37 32 pm" src="https://cloud.githubusercontent.com/assets/7506954/23591131/4a7fd2f4-01b1-11e7-982b-6cd8f4731463.png">
<img width="1280" alt="screen shot 2017-03-05 at 2 37 37 pm" src="https://cloud.githubusercontent.com/assets/7506954/23591130/4a7f98fc-01b1-11e7-951f-b62c0441d595.png">

<img width="283" alt="screen shot 2017-03-05 at 2 36 53 pm" src="https://cloud.githubusercontent.com/assets/7506954/23591125/34f95626-01b1-11e7-8971-63f19c6144f8.png">

**Comment by geekrishabh** [comment]
@sotomaque seems to work fine . Try the CRNA branch .
