### ISSUE TITLE
Did a fresh clone today, and I get a 'View' has no propType for native prop error

### ISSUE THREAD

**Issue by dekkofilms** [start-react/native-starter-kit#79]
react-native: 0.41.2
react: 15.4.2
native-base: 0.5.22

I just did a fresh clone:
```
$ git clone https://github.com/start-react/native-starter-kit.git
$ cd native-starter-kit/
$ npm install
$ react-native link
```

And then opened the project up through xCode (recommended on first use).

Build succeeded, but get this error on the simulator:

![screen shot 2017-03-09 at 9 53 47 am](https://cloud.githubusercontent.com/assets/14862852/23758938/e4fb310a-04b0-11e7-9542-539b88bd09c6.png)

**Comment by SupriyaKalghatgi** [comment]
@dekkofilms Check the latest update of NSK with RN 0.41 and NB 2.0
