### ISSUE TITLE
error running on simulator (android)

### ISSUE THREAD

**Issue by vesper8** [start-react/native-starter-kit#8]
Having so many problems getting this running.

I've done the react-native upgrade because was getting another issue, and now am getting this error:

<img width="679" alt="screenshot 2016-06-13 16 26 25" src="https://cloud.githubusercontent.com/assets/816028/16002840/dcc81922-3183-11e6-9098-e15d36dc3786.png">

any tips?

anything else you need to know?

running android studio on mac with a 6.0 emulated device

**Comment by sankhadeeproy007** [comment]
Which version of react-native are you using?

**Comment by vesper8** [comment]
so when I was experiencing other problems, I saw a lot of closed issues pointing to running react-native upgrade from the root project folder. When I tried to do that it told me I first needed to run 

npm install --save react

So I did, and then ran the upgrade command. And so below is my package.json in the root of the project

```
{
  "name": "NativeStarter",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "color": "^0.10.1",
    "react": "^15.1.0",
    "react-native": "0.25.1",
    "react-native-android-statusbar": "0.1.2",
    "react-native-drawer": "^1.16.6",
    "react-native-navbar": "^1.1.4",
    "react-native-router-flux": "^2.3.1",
    "react-native-selectme": "^1.0.0",
    "react-native-vector-icons": "1.0.0-rc"
  }
}
```

**Comment by sankhadeeproy007** [comment]
Hey can you clone the latest and check if it's working?

**Comment by johntom** [comment]
Will do and get back to you asap

**Comment by johntom** [comment]
1)I installed latest and tried to run against genymotion 5x-6.0.0- API 23
and 60-6.0.0.0 - API 23

2) c:\react\NativeStarterPro-v31\NativeStarterPro>react-native run-android
See e1
2a) I
changed C:\react\NativeStarterPro-v31\NativeStarterPro\android\settings.gradle
from / to
\
project(':react-native-code-push').projectDir = new
File(rootProject.projectDir,
'../node_modules/react-native-code-push/android/app') but get *e2

*e1
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat
installDebug...

FAILURE: Build failed with an exception.
- Where:
  Settings file
  'C:\react\NativeStarterPro-v31\NativeStarterPro\android\settings.gradle'
  line: 5
- What went wrong:
  Could not compile settings file
  'C:\react\NativeStarterPro-v31\NativeStarterPro\android\settings.gradle'.
  
  > startup failed:
  > settings file
  > 'C:\react\NativeStarterPro-v31\NativeStarterPro\android\settings.gradle':
  > 5: unexpected char: '\' @ line 5, column 121.
  >  modules\react-native-code-push\android\a
  >                                ^
  
  1 error
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or
  --debug
  option to get more log output.

BUILD FAILED

Total time: 1.378 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and
have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

c:\react\NativeStarterPro-v31\NativeStarterPro>

*e2

:app:generateDebugSources
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: ')' expected
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                      ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: <identifier> expected
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                           ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: illegal start of type
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                            ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: as of release 8, 'this' is allowed as the parameter name for the
receiver type only, which has to be the first parameter
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                              ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: ';' expected
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                                               ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: <identifier> expected
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                                                     ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: illegal start of type
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                                                      ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:41:
error: <identifier> expected
        new CodePush(${androidDeploymentKey}, this, BuildConfig.DEBUG),
                                                                       ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:42:
error: ';' expected
            new VectorIconsPackage(),
               ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:42:
error: illegal start of type
            new VectorIconsPackage(),
                                  ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:42:
error: <identifier> expected
            new VectorIconsPackage(),
                                   ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:42:
error: <identifier> expected
            new VectorIconsPackage(),
                                     ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:43:
error: invalid method declaration; return type required
            new CodePush(null, this, BuildConfig.DEBUG)
                ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:43:
error: illegal start of type
            new CodePush(null, this, BuildConfig.DEBUG)
                         ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:43:
error: illegal start of type
            new CodePush(null, this, BuildConfig.DEBUG)
                               ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:43:
error: <identifier> expected
            new CodePush(null, this, BuildConfig.DEBUG)
                                                      ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:43:
error: ';' expected
            new CodePush(null, this, BuildConfig.DEBUG)
                                                       ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:45:
error: ')' expected
    }
     ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:46:
error: reached end of file while parsing
}
 ^
C:\react\NativeStarterPro-v31\NativeStarterPro\android\app\src\main\java\com\nsp\MainActivity.java:47:
error: reached end of file while parsing
20 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:compileDebugJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or
  --debug
  option to get more log output.

BUILD FAILED

**Comment by johntom** [comment]
To be clear as I had a type this is how settings.gradle looks after the
change

include ':app'
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new
File(rootProject.projectDir,
'../node_modules/react-native-code-push/android/app')
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new
File(rootProject.projectDir,
'../node_modules/react-native-vector-icons/android')
include ':react-native-code-push'
project(':react-native-code-push').projectDir = new
File(rootProject.projectDir,
'../node_modules/react-native-code-push/android/app')

**Comment by johntom** [comment]
I also tried npm install -g rnpm to get version 1.9.0 but stll same issuesrnpm
linkrnpm linkn

**Comment by sanketsahu** [comment]
@johntom Thanks for all the help John! We are looking into it.

**Comment by sankhadeeproy007** [comment]
@johntom delete the Android directory. Run `react-native android`, replace the files it asks you to. Hit return/enter when it prompts you for the code-push deployment, `rnpm link`, you should be good to go.

**Comment by johntom** [comment]
Ok I did that and now get the following in settings.gradle
rootProject.name = 'NSP'
include ':app'

Android icon displays on phone WITH NSP undeneath but I just get the RN
Welcome to React native! form.

I replaced the settings.gradle but with same results.
John

**Comment by johntom** [comment]
Was never prompted about code-push

**Comment by SupriyaKalghatgi** [comment]
@johntom while running`react-native android`, you will be prompted to replace the files.
After that you got to overwrite the content of files those are being replaced.

**Comment by SupriyaKalghatgi** [comment]
Fixed with latest update
