### ISSUE TITLE
Help Migrating to 2.0.12.

### ISSUE THREAD

**Issue by pikitgb** [start-react/native-starter-kit#80]
Hi, in the package.json the version of native-base is 0.5.22
When trying to migrate to 2.0.X things break...
Any ideas or suggestions how to do this ? 

Thanks.

**Comment by acamenhas** [comment]
I'm waitting too for the native-starter-kit release update for native-base 2.0...

**Comment by SupriyaKalghatgi** [comment]
@pikitgb @acamenhas NSK is updated with RN 0.41 and NB 2.0

**Comment by pikitgb** [comment]
Terrific ! Thanks.
