### ISSUE TITLE
react-native run-android failed on Windows 10

### ISSUE THREAD

**Issue by samsudheen** [start-react/native-starter-kit#84]
starter kit does not work on android with windows 10 , no matter what I try:

Loading dependency graph, done.
Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░  89.2% (661/700)...(node:3828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2058): UnableToResolveError: Unable to resolve module D:\ReactNative\native-starter-kit\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js from D:\ReactNative\native-starter-kit\node_modules\socketcluster-client\lib\sctransport.js: Directory D:\ReactNative\native-starter-kit\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js doesn't exist
(node:3828) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js pBundling `index.android.js`

**Comment by SupriyaKalghatgi** [comment]
@samsudheen You could run it for iOS?

**Comment by sem-nowsquare** [comment]
I get the same error on Windows 10, iOS works fine.

**Comment by tdorado** [comment]
Same error for Windows 10, but ubuntu work fine

**Comment by thibbo** [comment]
I'm facing the same issue.

edit: downgrading remote-redux-devtools to version 0.5.0 with the following command fixes the issue: 
`npm install remote-redux-devtools@0.5.0 --save-dev`

**Comment by sem-nowsquare** [comment]
@thibbo that fixed it for me, too
