### ISSUE TITLE
NavigationExperimental is deprecated from 0.43

### ISSUE THREAD

**Issue by llioor** [start-react/native-starter-kit#87]
From react native docs:

> As of React Native 0.43, NavigationExperimental is deprecated. It will be removed from the codebase in a later version.

https://facebook.github.io/react-native/docs/navigation.html#navigationexperimental

1. What we should do with it? are we going to keep use it?
2. If yes, is there good DOCs for NavigationExperimental because I see in the project we use "popRoute, pushRoute, replaceAt" and I didn't find what is the differences between them.

Thank you.

**Comment by SupriyaKalghatgi** [comment]
@llioor Native Starter Kit will discontinue usage of NavigationExperimental from its next release.

You need to wait for next updates

**Comment by shivrajkumar** [comment]
@llioor You can check the latest. NavigationExperimental has beed removed and has been updated with React Native Router Flux.

**Comment by llioor** [comment]
@shivrajkumar Thank for the update.
So to use this package: https://github.com/aksonov/react-native-router-flux right?

**Comment by DFelten** [comment]
It would interest me, why you are using react-native-router-flux and not the upcoming [ReactNavigation](https://reactnavigation.org/), which will be a part of the main package of React Native as far as I know?

**Comment by llioor** [comment]
@DFelten There are many solutions outside but I spoke about the solution which includes in this "native-starter-kit"
https://reactnavigation.org/ is the best option right now.
Thanks

**Comment by DFelten** [comment]
Ok, thanks. I would be interested in such starter kit, which runs with React Navigation.
