### ISSUE TITLE
Error when try to run android on Windows 10

### ISSUE THREAD

**Issue by thienlhh** [start-react/native-starter-kit#88]
When I run the project with target to android and stuck at this error:

`Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░  60.3% (473/609)...(node:948) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2058): UnableToResolveError: Unable to resolve module D:\Workspace\native-starter-kit\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js from D:\Workspace\native-starter-kit\node_modules\socketcluster-client\lib\sctransport.js: Directory D:\Workspace\native-starter-kit\node_modules\socketcluster-client\lib\sctransportBundling `index.android.js``

**Comment by SupriyaKalghatgi** [comment]
@thienlhh Just to confirm, did you build successfully for iOS?

**Comment by thienlhh** [comment]
@SupriyaKalghatgi As I run on windows 10 then I can not run-ios, just run-android.

**Comment by jackyef** [comment]
@SupriyaKalghatgi The error in my case (#91) is different with this one. Why is my issue closed and referenced to this one?

**Comment by thienlhh** [comment]
To day I try to removed and re installed the repo and some how it works, not sure but I'm not see this error any more. May be the issue should be closed, thanks.
