### ISSUE TITLE
navigation slow down on physical devices?

### ISSUE THREAD

**Issue by ReneMarquez** [start-react/native-starter-kit#89]
Hello, just wondering if anyone has/had this kind of behaviour; I use the Native Starter Pro bundle (but I think the dependencies are pretty much the same as this one) so I don't know what can be causing this; app runs as expected on the simulator, but when I run it on a device, some transitions between screens take like 2-3 seconds (sometimes more), which is pretty bad cause I'm not even debugging the app

**Comment by SupriyaKalghatgi** [comment]
@ReneMarquez Please use GitStrap in case if you face issues with Native Starter Pro

**Comment by SupriyaKalghatgi** [comment]
@ReneMarquez Native Starter Kit is currently using NavigationExperimental for routing.
Which renders previous as well as the new pushed or replaced screen.

The very next update of Native Starter Kit will not have this
Please wait for the update

**Comment by shivrajkumar** [comment]
@ReneMarquez Native Starter Kit is updated with React Native Router Flux and latest versions of NativeBase. The performance issue is resolved with the latest version. Have a look.
