### ISSUE TITLE
Error on Android Emulator - Windows

### ISSUE THREAD

**Issue by kittugit** [start-react/native-starter-kit#9]
Tried to run it on android emulator on windows.. got the following exception... can someone help me to solve this error?
![native_base](https://cloud.githubusercontent.com/assets/3399549/16174008/ad17ec50-3577-11e6-8840-4ff5c7449929.PNG)

**Comment by sankhadeeproy007** [comment]
Are you sure you did rnpm link? We tried running it on our systems and it worked pretty fine. Did you try vector icons in any other project?

**Comment by kittugit** [comment]
Yes, I did rnpm link.. I didn't try vector icons in any other project..  i believe RNVectorIconModule is changed in react-native which is causing this issue..  Is it something to be fixed in react-native-vector-icons??

**Comment by sankhadeeproy007** [comment]
I would think so. Other people have run the app without any issues.

**Comment by SupriyaKalghatgi** [comment]
@kittugit Native Starter Kit has been updated
Try the latest version and let me know if you still face the same issue

**Comment by kittugit** [comment]
@SupriyaKalghatgi  Thanks for your reply..  I tried again today.. But no luck.. Still getting same error... 

git clone https://github.com/start-react/native-starter-kit.git
cd native-starter-kit
npm install
rnpm link
react-native run-android

Please let me know if I miss any steps..

**Comment by SupriyaKalghatgi** [comment]
@kittugit Is it working fine for iOS with the latest code?

**Comment by kittugit** [comment]
@SupriyaKalghatgi   Sorry.. i don't have Mac..

**Comment by kittugit** [comment]
@SupriyaKalghatgi .. I manage to solve the issue by overriding the following method in 
..\node_modules\react-native-vector-icons\android\src\main\java\com\oblador\vectoricons\VectorIconsModule.java

also some other modules in CodePush.. Will close this issue..

BTW: starter app is working as i expected... Thanks for your effort.. 

`@Override
  public boolean canOverrideExistingModule() {
    return true;
  }`

**Comment by johntom** [comment]
Hi Sankadeep & Kumar,
While all previous testing with apple seemed to be fine, the client
requested that I submit to apple store as they didn't want to register
anyones phones for a download Apple rejected stating that
1) 1.0 Binary Rejected Jul 22, 2016
Performance - 2.1 We discovered one or more bugs in your app when reviewed
on iPad and iPhone running iOS 9.3.3 on Wi-Fi connected to an
2) Jul 22, 2016 at 6:28 PM
From Apple
2. - 1 PERFORMANCE: APP COMPLETENESS
Performance - 2.1
We discovered one or more bugs in your app when reviewed on iPad and iPhone
running iOS 9.3.3 on Wi-Fi connected to an IPv6 network.

Specifically, the login button does not respond when selected.
[THIS IS FIXED]
Next Steps

Please run your app on a device while connected to an IPv6 network (all
apps must support IPv6) to identify the issue(s), then revise and resubmit
your app for review.

If we misunderstood the intended behavior of your app, please reply to this
message in Resolution Center to provide information on how these features
were intended to work.

For new apps, uninstall all previous versions of your app from a device,
then install and follow the steps to reproduce the issue(s). For updates,
install the new version as an update to the previous version, then follow
the steps to reproduce the issue(s).

Resources

For information about supporting IPv6 Networks, please refer to Supporting
IPv6 DNS64/NAT64 Networks and About Networking

If you have difficulty reproducing a reported issue, please try testing the
workflow described in Technical Q&A QA1764: How to reproduce bugs reported
against App Store submissions.

If you have code-level questions after utilizing the above resources, you
may wish to consult with Apple Developer Technical Support. When the DTS
engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

3) Based on above I've decided to rebuild app with the lastest version of
NSP but the password I have to login to strapmobile does not work on
gitstrap so I can't download on mac
4) If possible I'd like to setup a phone conference as I need to push this
out asap.
5) While not on latest version of NSP android app works great.
Thanks
John
212 989 7385

> ead
> https://github.com/notifications/unsubscribe/ABylgHoRzDbNBKgDLytVW45_Ba1soV5jks5qOhyTgaJpZM4I5C1o
> .
