### ISSUE TITLE
Can't get the sample up and running

### ISSUE THREAD

**Issue by jackyef** [start-react/native-starter-kit#91]
What I have done:
1. Clone the repo to a local folder
2. cd into the folder, run `npm install`
3. Run `react-native link`
4. Run `react-native run-android` 
5. Run `react-native run-android`

What I got:
Error from React Packager
```
Looking for JS files in
   D:\Projects\ReactNative\native-starter-kit

Loading dependency graph...
React packager ready.

Loading dependency graph, done.
Bundling `index.android.js`  100.0% (974/974), done.
 ERROR  EPERM: operation not permitted, lstat 'D:\Projects\ReactNative\native-starter-kit\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"D:\\Projects\\ReactNative\\native-starter-kit\\android\\app\\build\\intermediates\\incremental\\mergeDebugResources\\merged.dir\\values\\values.xml"}
Error: EPERM: operation not permitted, lstat 'D:\Projects\ReactNative\native-starter-kit\android\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml'
    at Error (native)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.
Press any key to continue . . .
```

I can't get the sample project deployed properly on my device. Notice that I run `react-native run-android` twice. 
The first time, the bundling finished, but my device only show white background with nothing whatsoever. Then I try to run it again.
The second, the react packager got an error.

Any idea about this?

**Comment by SupriyaKalghatgi** [comment]
#88

**Comment by geekrishabh** [comment]
Closing this Isssue Try the Branch CRNA  [For more details](https://github.com/react-community/create-react-native-app)
