### ISSUE TITLE
Error: with the same name across two different files.

### ISSUE THREAD

**Issue by araratmartirossyan** [start-react/native-starter-kit#95]
This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-vector-icons
  Paths: /Users/mac/projects/react/native-starter-kit/node_modules/react-native/local-cli/core/__fixtures__/files/package.json collides with /Users/mac/projects/react/native-starter-kit/node_modules/react-native-router-flux/node_modules/react-native/local-cli/core/__fixtures__/files/package.json

I was try on 3 devices to start this project, same problem. if i remove all packages.json from node_modules/react-native this start working

**Comment by zak10** [comment]
Getting the same problem, FYI

**Comment by shivrajkumar** [comment]
@myfailemtions @zak10 The issue seem to be with the latest version of `react-native-router-flux`. You can fix RNRF to v3.38.0. That will resolve the issue

**Comment by geekrishabh** [comment]
@myfailemtions @zak10 you guys can try the CRNA branch [For more](https://github.com/react-community/create-react-native-app)
