### ISSUE TITLE
ActionSheet and Toast do not work reliably in apps based on this architecture.

### ISSUE THREAD

**Issue by TomMahle** [start-react/native-starter-kit#96]
This is based on an issue thread on NativeBase: https://github.com/GeekyAnts/NativeBase/issues/739

Because of the animations between pages in apps based on :

```
Container 1 Mounts              Unmounts
|-------------------------------|
                            |-----------------------...
                            Container 2 Mounts
```
As a component unmounts in React, it runs its ref function with 'null'. This is causing the error that we're seeing in the linked thread, since there is a single class of ActionSheet with an instance bound to it, and the animations between pages mean that the unmount is the most recent ref-defining event, setting it to null.

The fix in my case was to wrap the app in a single container that lives above the AppNavigator and replace the per-page containers with views. A little bit of styling later and the app was back to looking the same and the ActionSheet was working as expected! Could we make this change in the starter-kit to get people started off on the right foot for being able to use those components? Thanks for making such an excellent scaffold for getting an app up and running!

**Comment by SupriyaKalghatgi** [comment]
Toast #[819](https://github.com/GeekyAnts/NativeBase/issues/819)
ActionSheet #[739](https://github.com/GeekyAnts/NativeBase/issues/739)
