### ISSUE TITLE
How to move from NavigationExperimental to RNRF

### ISSUE THREAD

**Issue by vvusts** [start-react/native-starter-kit#99]
I created a project with this starter kit.
Now when NavigationExperimental is gone what steps should I take to move from NavigationExperimental to RNRF.
**Should I npm install something**, change imports, replace code?
For example I have:
```
import {actions} from 'react-native-navigation-redux-helpers';
const {reset, pushRoute} = actions;
reset: key => dispatch(reset([
          {
            key: 'HomeScene'
          }
      ], key, 0))
```
or
```
this.props.pushRoute({
            key: route,
        }, this.props.navigation.key);
```
Do I need to change code now or import?
Will '**react-native-navigation-redux-helpers**' still be used?

**Comment by geekrishabh** [comment]
@vvusts  you can have a look at the [RNRF branch](https://github.com/start-react/native-starter-kit/tree/RNRF) or the [CRNA branch](https://github.com/start-react/native-starter-kit/tree/CRNA) .The above will solve your issue .
